### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Pandry** [Scienza/scienziati_bot#9]
- [ ] Forwarding to channel - Takes a comment and forwards to an hardcoded channel the message and a link to the message replied to
- [ ] Save referred message- makes the bot stateful, requires a change in the DB structure
- [ ] Print logs about the actions the bot takes
- [ ] Save for later - saves a message from the group to get it later on
